---
#
# tasks file for ansible-role-ulimits_setup
#
# vim:et:ts=2:ft=ansible

- name: Create limits.conf entries
  pam_limits: domain="{{ item.domain }}" limit_type="{{ item.type }}" limit_item="{{ item.item }}" value="{{ item.value }}"
  with_items: "{{ _ulimits_setup.limits }}"

- name: Add pam_limits module to common session configs
  lineinfile: dest='/etc/pam.d/{{ item }}' line='session required pam_limits.so' insertbefore='# end of pam-auth-update config'
  with_items:
    - "common-session"
    - "common-session-noninteractive"

